environment: "development"

db:
  host: "localhost"
  port: "5432"
  user: "myuser"
  password: "mypassword"
  dbname: "mydb"
  sslmode: "disable"
  max_conns: 20
  min_conns: 1

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
  max_retries: 3
  pool_size: 100
  min_idle_conns: 10
  dial_time_out: 5
  read_time_out: 3
  write_time_out: 3
  idle_time_out: 5

arango:
  db_name: "arangodb"
  conn_strs: "tcp://127.0.0.1:8529,http://198.51.100.1:8529"
  insecure_skip_verify: true
  user: "root"
  password: "root"

# You will only need this in production.
logger:
  level: "info"
  encoder_config:
    message_key: "msg"
    level_key: "level"
    name_key: "logger"
  rotation_config:
    filename: "var/lib/test.txt"
    max_size: 500
    max_backups: 2
    max_age: 1
  fluentbit_config:
    host: "fluent-bit"
    port: 24224
    tag: "test.template"

tracer:
  service_name: "test"
  insecure: "true"
  collector_url: "localhost:4317"

